/**
 * GENERATED by `scripts/gen-persistence-catalog.ts` — do not edit by hand; run
 * `pnpm run gen-persistence-catalog` to regenerate (verified fresh by
 * `pnpm run verify-persistence-catalog`, part of `doc-sync`).
 * @module @deepseek-ai/dsh-session/known-event-types
 */

/**
 * Every `SessionEventMap` member declared in this repository and the npm
 * package that supplies its semantics. The persistence read path refuses to
 * interpret a log containing a type outside this set unless the event
 * carries the envelope's `ignorable` marker (see `SessionEvent.ignorable`
 * in `./types.ts`): such a log was likely written by a newer harness, and
 * silently skipping a required event would reconstruct a wrong session.
 * Downstream plugin events are outside this map by construction and join
 * the runtime vocabulary through `ctx.sessions.eventTypes.register()`.
 */
export const KNOWN_SESSION_EVENT_TYPE_OWNERS: ReadonlyMap<string, string> = new Map([
  ['agent-preset/selected', '@deepseek-ai/dsh-agent-presets'],
  ['agent/inbox/spliced', '@deepseek-ai/dsh-agent'],
  ['approval/asked', '@deepseek-ai/dsh-user-approval'],
  ['approval/decided', '@deepseek-ai/dsh-user-approval'],
  ['approval/policy', '@deepseek-ai/dsh-user-approval'],
  ['assistant/chunk', '@deepseek-ai/dsh-session'],
  ['assistant/message', '@deepseek-ai/dsh-session'],
  ['blueprint/apply-result', '@deepseek-ai/dsh-blueprint-adapter'],
  ['blueprint/capability-authoring', '@deepseek-ai/dsh-blueprint-adapter'],
  ['blueprint/capability-cancel-requested', '@deepseek-ai/dsh-blueprint-adapter'],
  ['blueprint/capability-repair', '@deepseek-ai/dsh-blueprint-adapter'],
  ['blueprint/capability-verified', '@deepseek-ai/dsh-blueprint-adapter'],
  ['blueprint/creator-authoring', '@deepseek-ai/dsh-blueprint-adapter'],
  ['blueprint/creator-authoring-ended', '@deepseek-ai/dsh-blueprint-adapter'],
  ['blueprint/proposal-cancelled', '@deepseek-ai/dsh-blueprint-adapter'],
  ['blueprint/route-decision', '@deepseek-ai/dsh-blueprint-adapter'],
  ['blueprint/routing-input', '@deepseek-ai/dsh-blueprint-adapter'],
  ['blueprint/user-change', '@deepseek-ai/dsh-blueprint-adapter'],
  ['command/done', '@deepseek-ai/dsh-commands'],
  ['command/run', '@deepseek-ai/dsh-commands'],
  ['compaction/end', '@deepseek-ai/dsh-compaction'],
  ['compaction/prune', '@deepseek-ai/dsh-compaction'],
  ['compaction/start', '@deepseek-ai/dsh-compaction'],
  ['compaction/summary', '@deepseek-ai/dsh-compaction'],
  ['feedback/record', '@deepseek-ai/dsh-command-feedback'],
  ['goal/change', '@deepseek-ai/dsh-goal'],
  ['hook/invoked', '@deepseek-ai/dsh-hook-protocol'],
  ['hook/result', '@deepseek-ai/dsh-hook-protocol'],
  ['llm/retry', '@deepseek-ai/dsh-llm-retry'],
  ['llm/retry-started', '@deepseek-ai/dsh-llm-retry'],
  ['permission/preset', '@deepseek-ai/dsh-permission-presets'],
  ['plan/mode', '@deepseek-ai/dsh-plan-mode'],
  ['request/context', '@deepseek-ai/dsh-session'],
  ['request/header', '@deepseek-ai/dsh-session'],
  ['sandbox/mode', '@deepseek-ai/dsh-sandbox-policy'],
  ['schedule/change', '@deepseek-ai/dsh-schedule'],
  ['session/end-seed', '@deepseek-ai/dsh-session'],
  ['session/title', '@deepseek-ai/dsh-session-title'],
  ['session/title-llm-request', '@deepseek-ai/dsh-session-title-llm'],
  ['step/end', '@deepseek-ai/dsh-session'],
  ['step/start', '@deepseek-ai/dsh-session'],
  ['subagent/descriptor', '@deepseek-ai/dsh-subagent'],
  ['todo/write', '@deepseek-ai/dsh-session'],
  ['tool-workflow/agent-end', '@deepseek-ai/dsh-tool-workflow'],
  ['tool-workflow/agent-start', '@deepseek-ai/dsh-tool-workflow'],
  ['tool-workflow/run-end', '@deepseek-ai/dsh-tool-workflow'],
  ['tool-workflow/run-start', '@deepseek-ai/dsh-tool-workflow'],
  ['tool/call', '@deepseek-ai/dsh-session'],
  ['tool/code-dispatch', '@deepseek-ai/dsh-tools'],
  ['tool/code-dispatch-start', '@deepseek-ai/dsh-tools'],
  ['tool/result', '@deepseek-ai/dsh-session'],
  ['turn/end', '@deepseek-ai/dsh-session'],
  ['turn/start', '@deepseek-ai/dsh-session'],
  ['user/message', '@deepseek-ai/dsh-session'],
  ['web/deepseek-search-llm-request', '@deepseek-ai/dsh-web-search-deepseek'],
])

/** Event types whose semantics are supplied by packages in this build. */
export const KNOWN_SESSION_EVENT_TYPES: ReadonlySet<string> = new Set([
  ...KNOWN_SESSION_EVENT_TYPE_OWNERS.keys(),
])
